### PR TITLE
Add versions.txt update CurrentInstallableVersion.txt

### PR DESCRIPTION
**Pull request by Y2Kwastaken**
versions.txt provides a list of all downloadable versions. This is useful when attempting to download older versions and verifying they exist in this repository. CurrentInstallableVersions.txt has been upgraded to 0.1.9 it was previously behind by 2 versions. To make this repo usable I highly recommenced ensuring these files are updating

### CODE REVIEW

**Comment by EmmaTheMartian** [comment]
You can just reference the raw versions.json and find both of that info there. Is there some other reason why you can't do that? /lh

I realize this is the archive, not meta info... sorry about that 😭

**Comment by Y2Kwastaken** [comment]
> You can just reference the raw versions.json and find both of that info there. Is there some other reason why you can't do that? /lh

Forcing People to create an itch.io API key for tooling isn't exactly user friendly.

> I realize this is the archive, not meta info... sorry about that 😭

If you don't want to provide MetaData remove the CurrentInstallableVersion.txt which is clearly metadata

**Comment by EmmaTheMartian** [comment]
Yeah I realized my mistake, I thought this was a different repo for a second. That's on me

I do think this PR is beneficial though

**Comment by Mr-Zombii** [comment]
The pull request looks good I'm going to merge it in

**Pull request merged**
